site_name: recall-sdk
repo_url: https://github.com/recallnet/py-recall
site_url: https://recallnet.github.io/py-recall
site_description: Python client for Recall Network storage & operations
site_author: Recall Network Contributors
edit_uri: edit/main/docs/
repo_name: recallnet/py-recall
copyright: Maintained by <a href="https://textile.io">Textile</a>.

nav:
    - Home: index.md
    - Modules: modules.md
plugins:
    - search
    - mkdocstrings:
          handlers:
              python:
                  paths: ["src/recall_sdk"]
theme:
    name: material
    feature:
        tabs: true
    palette:
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: white
          accent: deep orange
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: black
          accent: deep orange
          toggle:
              icon: material/brightness-4
              name: Switch to light mode
    icon:
        repo: fontawesome/brands/github

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/recallnet/py-recall
        - icon: fontawesome/brands/python
          link: https://pypi.org/project/py-recall

markdown_extensions:
    - toc:
          permalink: true
    - pymdownx.arithmatex:
          generic: true
